### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by sabuto** [lebaston100/node-red-contrib-obs-ws#1]
Hi, I am trying to get this setup locally but i cannot seem to figure it out, since this isn't published on npm i have cloned this repo into a local folder, gone into node red and npm installed but when i boot i get:

 [node-red-contrib-obs-ws/obs-ws] Error: Cannot find module 'obs-websocket-js'

do i have to manually install obs-websocket-js somewhere? because in my node_models for node-red it has installed it there?

**Comment by lebaston100** [comment]
In theory it should it when npm installing the unziped folder as it's listed as a dependency.
I have another simular report though so i will look into it.
For now doing a "npm install obs-websocket-js --save" in the .node-red folder should be enough.

**Comment by sabuto** [comment]
hmm i still seem to get the not found issue for some reason, do i need to do npm install in the local dir for this git repo?

**Comment by lebaston100** [comment]
I'm actually not sure, as seem by the code quality i'm not that big of a node expert. I'd suggest you try it, maybe even a "npm i" when cd'd into the folder should be enough.

**Comment by sabuto** [comment]
ok that worked :D awesome

**Comment by sabuto** [comment]
just instead of opening another issue are you open to PR's on this?

**Comment by lebaston100** [comment]
What exactly would you PR? Is there an issue in the package.json?
I'm currently not really open to PR's to the program code itself as i want to do an entire re-write before adding any more functionality (and doing the npm publishing) .

**Comment by sabuto** [comment]
ahh fair enough, it would be adding a output to send data because atm you have non data nodes so like get version etc but to change scene i would like to add that functionality. no worries if not i'll just add it locally

**Comment by lebaston100** [comment]
There is a SetCurrentScene Node is that sufficiant?
Otherwise you can just use the raw request node and pack it into a subflow with a change node before it.

**Comment by sabuto** [comment]
yeah for sure would work i'll give it a go, just think it would be easier if it was maybe organised like the nodata node with dropdown so people could find it easier if they didnt want to dig through the documentation

**Comment by lebaston100** [comment]
There is no documentation as of yet ;D
I won't bother with it for now, at last i need to get this whole thing on a better codebase so it's easier to add that sort of stuff. Maybe even dynamically generate it, we'll see.

**Comment by sabuto** [comment]
> There is no documentation as of yet ;D
> I won't bother with it for now, at last i need to get this whole thing on a better codebase so it's easier to add that sort of stuff. Maybe even dynamically generate it, we'll see.

no i meant the websocket documentation :P

**Comment by lebaston100** [comment]
Oh i see, well right now this is a pretty essential tool to work with it in general. I have some ideas but at this point lack the knowledge on how to implement them in a resonable matter.
