### ISSUE TITLE
May you write an example?

### ISSUE THREAD

**Issue by Barabba11** [lebaston100/node-red-contrib-obs-ws#2]
Hi, thank you for this module, can I kindly ask you to write an example?
I would use it with Alexa to change scene in OBS, I suppose I have to inject an object with in msg.payload the http string containing the name of the scene. 
Thank you for help

**Comment by lebaston100** [comment]
Here is one. You bascially just use the SetCurrentScene Node and configure it to use msg.payload as the scene name.
Then make sure the data coming from the alexa node has the scene name(Just a String) in the msg.payload and that should be it.

`[{"id":"a9be736b.cf58d","type":"SetCurrentScene","z":"2d02afb5.335e6","name":"","scene":"payload","sceneType":"msg","obsInstance":"ec74e29c.63b01","x":770,"y":800,"wires":[[]]},{"id":"76914e3.cb211b","type":"inject","z":"2d02afb5.335e6","name":"Alexa Data","props":[{"p":"payload"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"OBSsceneName","payloadType":"str","x":570,"y":800,"wires":[["a9be736b.cf58d"]]},{"id":"ec74e29c.63b01","type":"obs-instance","d":true,"name":"OBSinstance","host":"localhost","port":"4444"}]`

**Comment by Barabba11** [comment]
thank you! It's perfectly clear. Sorry the question llok stupid, the reason is that I didn't see your modules appearing on NR and I guess it was the module named "websocket out"

**Comment by lebaston100** [comment]
Ah, that makes sense. Hope i could help.
