### ISSUE TITLE
OBS raw request broken in node-red 3.0.2

### ISSUE THREAD

**Issue by JvPeek** [lebaston100/node-red-contrib-obs-ws#3]
Ohai,

i found an issue when using the "obs raw request"-node. It just doesn't accept any data. The error message states "Wrong data type. Needs to be a valid json object. Is: "string"" when i'm clearly inputting JSON data.

I've tested this on a fresh install.
``` Node-RED version: v3.0.2
Node.js  version: v16.16.0
Linux 5.4.0-122-generic x64 LE
OBS 27.1.3 at 64 bit Ubuntu via snap (yeah, i know)
```

I have attached a screenshot of the issue.

![2022-08-16-200923_1900x996_scrot](https://user-images.githubusercontent.com/71159838/184949880-039f1cd0-9d61-45fe-9a29-35b88756abcc.png)

Let me know if you need anything else.

**Comment by lebaston100** [comment]
Thanks for the report. Does it work if you import the sample/test flow?
I probably won't look into it for now since i have a local branch for obs-websocket v5 compatibility that i want to push soon and will probably test everything then anyways but i'll keep it in mind when testing

**Comment by JvPeek** [comment]
I think i found the problem. By default the node doesn't have an input source selected:
![2022-08-16-234706_362x209_scrot](https://user-images.githubusercontent.com/71159838/184991211-0bf35515-753c-4596-b663-a59288433073.png)
So it says only `payload` instead of `msg.payload`

With that fixed, everything works. So.. user error :(
I am the problem. I was the problem the whole time. Now i feel bad.

Sorry for wasting your time.

**Comment by lebaston100** [comment]
No worries. It seems like the typedInput is broken though, it should look differently, i'll look into that some time.
