### ISSUE TITLE
RequestBatch?

### ISSUE THREAD

**Issue by willyk0** [lebaston100/node-red-contrib-obs-ws#4]
As far as I can see, there can be only done simple requests, without batching. In 5.0.x the RequestBatch is no longer a request, it has its unique ID. I miss also "Sleep" Request. 

With ws 4.9.1 and 0.1.0, I could make a simple batch request to p.e change a text, change its visibility, sleep for some seconds, and turn the visibility off in just a couple of nodes. Doing the same with 5.0 an 0.2.4 I need to perform various calls to get text ID as a SceneItem and then do each step in single nodes. Complex requests now needs dozens of nodes!. It's a real disaster if you have hundreds of batches to make a complex bot!

So please, could we have batch functionality back or give us a workaround? Please.

I'll try to downgrade everything meanwhile.

**Comment by lebaston100** [comment]
Thanks for the suggestion. I never used the batch request in 4.x so i didn't even have it on the radar. Also when i did the main work migrating to obs-websocket 5 there was no support for batch requests in obs-websocket-js which only recently (2 weeks) added support for them. I'll look into what i can do. Would you be able to provide me with a sample flow how you generated your batch requests in 4.x? There would be several possibilities on how i could implement batch requests into the request node ranging from simple to fairly complicated.
The Sleep request is deliberately left out of the dropdown list because it currently has no use without batch support.

**Comment by willyk0** [comment]
Of course. 

I prepare the JSON with the batch of actions needed for that moment and then inject to a obs raw node. I'm attaching a very simple case, just receiving a command from twitch and triggering some actions in OBS like showing sources, activating filters... then waiting some seconds and finally go backwards hiding everything we showed. 

![image](https://user-images.githubusercontent.com/36780515/195484417-4c159bdc-4ded-4b60-8a0f-913c104e1d0b.png)

Content of "PROMO ON" node:

{
    "request-type": "ExecuteBatch",
    "requests": [
        {
            "request-type": "SetSceneItemRender",
            "scene-name": "1CAM",
            "source": "Espejo OVERLAY",
            "render": true
        },
        {
            "request-type": "SetSceneItemRender",
            "scene-name": "1CAM",
            "source": "Espejo CAMARA",
            "render": true
        },
        {
            "request-type": "SetSceneItemRender",
            "scene-name": "1CAM",
            "source": "FALDON",
            "render": true
        },
        {
            "request-type": "SetSourceFilterVisibility",
            "sourceName": "GrupoEscena",
            "filterName": "Torcido",
            "filterEnabled": true
        },
        {
            "request-type": "Sleep",
            "sleepMillis": 500
        },
        {
            "request-type": "SetSceneItemRender",
            "scene-name": "1CAM",
            "source": "Grupo PROMO",
            "render": true
        },
        {
            "request-type": "Sleep",
            "sleepMillis": 15000
        },
        {
            "request-type": "SetSceneItemRender",
            "scene-name": "1CAM",
            "source": "Grupo PROMO",
            "render": false
        },
        {
            "request-type": "Sleep",
            "sleepMillis": 500
        },
        {
            "request-type": "SetSourceFilterVisibility",
            "sourceName": "GrupoEscena",
            "filterName": "Recto",
            "filterEnabled": true
        },
        {
            "request-type": "SetSceneItemRender",
            "scene-name": "1CAM",
            "source": "FALDON",
            "render": false
        },
        {
            "request-type": "Sleep",
            "sleepMillis": 3500
        },
        {
            "request-type": "SetSceneItemRender",
            "scene-name": "1CAM",
            "source": "Espejo OVERLAY",
            "render": false
        },
        {
            "request-type": "SetSceneItemRender",
            "scene-name": "1CAM",
            "source": "Espejo CAMARA",
            "render": false
        }
    ]
}

Without batch, just for this little example I should have 14 nodes more to get the same result.

**Comment by lebaston100** [comment]
Thank you very much. I'll look into what i can do.

**Comment by lebaston100** [comment]
So i did a thing. You can give it a test if you want, right now it's published to the dev tag or https://www.npmjs.com/package/node-red-contrib-obs-ws/v/0.2.5

**Comment by willyk0** [comment]
> So i did a thing. You can give it a test if you want, right now it's published to the dev tag or https://www.npmjs.com/package/node-red-contrib-obs-ws/v/0.2.5

I'll take a look hopefully next week, I need to set up a virtual environment for testing :) Thank you so much!

**Comment by willyk0** [comment]
Sorry for the delay, finally I could test it. Really impressive work! Works like a charm in my setup! And it's very intuitive, thank you!!

**Comment by lebaston100** [comment]
Done with https://github.com/lebaston100/node-red-contrib-obs-ws/releases/tag/v0.2.7
