### ISSUE TITLE
Error: Socket not identified

### ISSUE THREAD

**Issue by HrKnuddel** [lebaston100/node-red-contrib-obs-ws#5]
the Websocket is not connecting and in the node-red-log (with log settings on trace) only says the following:
````
[trace] [obs-instance:OBS @ 187.2:4455] Trying to connect to obs
[trace] [obs-instance:OBS @ 187.2:4455] ConnectionClosed obs event
[trace] [obs-instance:OBS @ 187.2:4455] Error
[trace] [obs-instance:OBS @ 187.2:4455] Starting obsReconnector because ConnectionClosed event
````
When I time a request right, I can see the Error: "Error: Socket not identified" through the error output.
My OBS-WS config is with port 4455 and I deactivated the password

**Comment by lebaston100** [comment]
What does the obs log output when you enable the debug logging in the websocket settings (and then restart node-red)?
Can you connect with any other client?

**Comment by HrKnuddel** [comment]
the typical programmer thing happened and now it's working. In the old log where it doesn't work, I found nothing about a connection from my Node-Red. I also tested it with other clients, and it is working perfectly fine there.

**Comment by lebaston100** [comment]
Glad it works now.
